# День 8. Обучение на гигабайтах с Vowpal Wabbit

Batch gradient descend - градиент считается по сумме всех объектов
miniBatch DG () - градиент считается по сумме k-объектов
Stochastic GD (SGD) - градиент считается по одному объекту

In [1]:
import numpy as np
from scipy.sparse import csr_matrix

In [2]:
a = np.zeros([5,5])

In [3]:
a

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [6]:
a[0, 1] = 1
a[4, 2] = 3
a[3, 3] = 1
a[0, 4] = 2
a[1, 2] = 1

In [7]:
a

array([[ 0.,  1.,  0.,  0.,  2.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  3.,  0.,  0.]])

a = плотная матрица (много нулей, едининче значимые значения)

In [8]:
b = csr_matrix(a)

In [9]:
b

<5x5 sparse matrix of type '<class 'numpy.float64'>'
	with 5 stored elements in Compressed Sparse Row format>

In [15]:
b.todense()

matrix([[ 0.,  1.,  0.,  0.,  2.],
        [ 0.,  0.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  1.,  0.],
        [ 0.,  0.,  3.,  0.,  0.]])

In [16]:
b.nonzero()

(array([0, 0, 1, 3, 4], dtype=int32), array([1, 4, 2, 3, 2], dtype=int32))

первый массив - номера строк с нунелывыми элементами, второй - номера столцов

In [17]:
b.data

array([ 1.,  2.,  1.,  1.,  3.])

Значения ненулевых жлементов

---

In [19]:
from sklearn.datasets import load_files